# Generated by Django 3.2.9 on 2021-12-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['birthday'], name='profiles_ap_birthda_381f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['gender'], name='profiles_ap_gender_01e924_idx'),
        ),
    ]
