# Generated by Django 3.2.9 on 2021-12-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles_app', '0002_auto_20211217_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates that this user account is activated'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False,
                                      help_text='Designates that this user has access to the admin panel.'),
        ),
    ]
