# Generated by Django 3.2.9 on 2022-01-02 07:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles_app', '0003_auto_20211228_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='version',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
