# Generated by Django 3.2.9 on 2022-01-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0004_userprofile_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, help_text='Designates that user email is confirmed'),
        ),
    ]
