# Generated by Django 4.0.8 on 2022-10-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0007_auto_20220124_1235'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['first_name', 'last_name'], name='profiles_ap_first_n_9a3c5e_idx'),
        ),
    ]
